name: katas
description: >-
  The katas directory.
version: 0.6.1
publish_to: none
repository: https://github.com/psygo/dart_katas
homepage: https://github.com/psygo/dart_katas
issue_tracker: https://github.com/psygo/dart_katas/issues
documentation: https://github.com/psygo/dart_katas

environment:
  sdk: ">=3.2.4 <4.0.0"

dev_dependencies:
  test: any

dependencies:
  bowling_game:
    path: bowling_game/
  design_patterns:
    path: design_patterns/
  dungeon_problem:
    path: dungeon_problem/
  eratos_sieve:
    path: eratos_sieve/
  erlang:
    path: erlang/
  fizzbuzz:
    path: fizzbuzz/
  game_of_life:
    path: game_of_life/
  genetic_algorithm:
    path: genetic_algorithm/
  prime_factors:
    path: prime_factors/
  skiena:
    path: skiena/
  tic_tac_toe:
    path: tic_tac_toe/