name: dart_katas
description: >-
  These are coding exercises meant to sharpen your programming abilities, 
  analogous to martial arts'. 
  All of the katas were done using TDD, meaning they are not only tested by were
  tailored for (driven by) them.
version: 0.6.1
publish_to: none
repository: https://github.com/psygo/dart_katas
homepage: https://github.com/psygo/dart_katas
issue_tracker: https://github.com/psygo/dart_katas/issues

environment:
  sdk: ">=3.2.4 <4.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: any

dependencies:
  katas:
    path: katas/