name: tic_tac_toe
description: >-
  A kata attempt at recreating the game of Tic Tac Toe.
version: 0.0.1

repository: https://github.com/psygo/dart_katas
homepage: https://github.com/psygo/dart_katas
issue_tracker: https://github.com/psygo/dart_katas/issues
documentation: https://github.com/psygo/dart_katas

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  meta: any

dev_dependencies:
  test: any