name: genetic_algorithm
description: >-
  OOP Kata for the genetic algorithm. Based on [this post](https://lethain.com/genetic-algorithms-cool-name-damn-simple/).
version: 0.0.1

repository: https://github.com/psygo/dart_katas
homepage: https://github.com/psygo/dart_katas
issue_tracker: https://github.com/psygo/dart_katas/issues
documentation: https://github.com/psygo/dart_katas

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  meta: any
  rxdart: any
  
dev_dependencies:
  collection: any
  test: any